# Generated by Django 2.2.28 on 2023-09-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hello'),
    ]

    operations = [
        migrations.AddField(
            model_name='hello',
            name='python',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
